"""change user_name to username

Revision ID: 02c75cdf3eeb
Revises: 18a43d60544c
Create Date: 2020-10-18 15:07:57.301658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02c75cdf3eeb'
down_revision = '18a43d60544c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('ix_users_user_name', table_name='users')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', mysql.VARCHAR(length=255), nullable=False))
    op.create_index('ix_users_user_name', 'users', ['user_name'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
